url: www.opentechschool.org
baseurl: /www.opentechschool.org/
blog_domain: blog.opentechschool.org
css_version: 6

encoding: UTF-8
exlude: ['scripts', 'sass', 'config.rb', 'Gemfile', 'Gemfile.lock']

